/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'doc',
      label: 'Home',
      id: 'home/horizon',
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'tutorials/how-to-install',
          label: 'how to install',
        },
        {
          type: 'doc',
          id: 'tutorials/how-to-deploy-your-first-workload',
          label: 'how to deploy your first workload',
        }
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'concepts/overview',
          label: 'overview',
        },
        {
          type: 'doc',
          id: 'concepts/basics',
          label: 'basic concepts',
        }
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Administrator',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'user-guide/administrator/idp',
              label: 'identity providor',
            },
            {
              type: 'doc',
              id: 'user-guide/administrator/environment',
              label: 'environments',
            },
            {
              type: 'doc',
              id: 'user-guide/administrator/registry',
              label: 'registries',
            },
            {
              type: 'doc',
              id: 'user-guide/administrator/kubernetes',
              label: 'kubernetes',
            },
            {
              type: 'doc',
              id: 'user-guide/administrator/user-management',
              label: 'users',
            }
          ],
        },
        {
          type: 'category',
          label: 'Common User',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'user-guide/common-user/group',
              label: 'group',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/application',
              label: 'application',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/cluster',
              label: 'cluster',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/deploy-and-pod-management',
              label: 'deploy and manage pods',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/monitor',
              label: 'monitor',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/member',
              label: 'member',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/access-token',
              label: 'access Token',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/template',
              label: 'template',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/oauth-app',
              label: 'oauth app',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/webhook',
              label: 'webhook',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/user-space',
              label: 'user space',
            }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'API',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'reference/api/use-the-apis',
              label: 'use the API',
            },
            {
              type: 'doc',
              id: 'reference/api/apis',
              label: 'horizon apis',
            }
          ]
        },
        {
          type: 'category',
          label: 'template',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'reference/template/specification',
              label: 'specification',
            }
          ]
        }
      ],
    },
  ],
};

module.exports = sidebars;
