/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    {
      type: 'doc',
      label: 'Home',
      id: 'home/horizon',
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'How to Install',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'tutorials/how-to-install/local-installation',
              label: 'Local Installation',
            },
            {
              type: 'doc',
              id: 'tutorials/how-to-install/cloud-provider-installation',
              label: 'Cloud Provider Installation',
            }
          ]
        },
        {
          type: 'doc',
          id: 'tutorials/how-to-deploy-your-first-workload',
          label: 'How to Deploy Your First Workload',
        },
        {
          type: 'doc',
          id: 'tutorials/custom-ci',
          label: 'Custom CI',
        }
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Administrator',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'user-guide/administrator/idp',
              label: 'Identity Providor',
            },
            {
              type: 'doc',
              id: 'user-guide/administrator/environment',
              label: 'Environments',
            },
            {
              type: 'doc',
              id: 'user-guide/administrator/registry',
              label: 'Registries',
            },
            {
              type: 'doc',
              id: 'user-guide/administrator/kubernetes',
              label: 'Kubernetes',
            },
            {
              type: 'doc',
              id: 'user-guide/administrator/user-management',
              label: 'User Management',
            }
          ],
        },
        {
          type: 'category',
          label: 'Common User',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'user-guide/common-user/group',
              label: 'Group',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/application',
              label: 'Application',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/cluster',
              label: 'Cluster',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/deploy-and-pod-management',
              label: 'Deploy and Manage Pods',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/trigger',
              label: 'Trigger',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/monitor',
              label: 'Monitor',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/member',
              label: 'Member',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/access-token',
              label: 'Access Token',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/template',
              label: 'Template',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/oauth-app',
              label: 'Oauth App',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/webhook',
              label: 'Webhook',
            },
            {
              type: 'doc',
              id: 'user-guide/common-user/user-space',
              label: 'User Space',
            }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'API',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'reference/api/use-the-apis',
              label: 'Use APIs',
            },
            {
              type: 'doc',
              id: 'reference/api/apis',
              label: 'Horizon APIs',
            }
          ]
        },
        {
          type: 'category',
          label: 'Template',
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'reference/template/specification',
              label: 'Specification',
            }
          ]
        }
      ],
    },
  ],
};

module.exports = sidebars;
